### PR TITLE
Add parse domain feature

### PR DESCRIPTION
**Pull request by debuggings**
Eg. From **https://addons.mozilla.org/en-US/firefox/** you might want to go to **https://mozilla.org/**

### CODE REVIEW

**Comment by PerfectSlayer** [comment]
Hi @debuggings,

Thanks for the PR! It's a feature I forgot to implement when I port to WebExtensions.
I have no time right now to test and merge it but I will in a near future! 😉 

One last thing, and I don't have the answer, it's more to discuss about it but I previously add the "www." when missing. Should we keep it?
Check [the source code](https://github.com/PerfectSlayer/scrollupfolder/blob/addon-sdk/index.js#L665) and [the expected result](https://github.com/PerfectSlayer/scrollupfolder/blob/addon-sdk/test/test-main.js#L40) to see more details about this case.

**Comment by debuggings** [comment]
Hi,

I think there is no need to keep the "www.", because it is another branch of the origin URL. Just like https://addons.mozilla.org/en-US/firefox/themes and "https://addons.mozilla.org/en-US/firefox/extensions. 

The only difference is that it is very common that many sites have set their main domain started with "www". But it is also very common that URLs without "www" should automatically jump to the URL with "www", like facebook. More over, there are sites, like twitter, whoes main domains don't have the "www" part, so we should not add the "www" too.

**Comment by PerfectSlayer** [comment]
Ok, you convince me! 
I'll build the a version the next week and prepare changelog and usage wiki pages update.
Thanks!

**Comment by PerfectSlayer** [comment]
Hi just found and fix an issue about the settings loading. It prevents your feature to be enabled by default.

The settings which was loaded does not contains the key `parseDomain` so the applySettings() function disable it:
```javascript
/**
 * Apply the settings.
 * @param settings The settings to apply.
 */
function applySettings(settings) {
	// Update current settings
	displayUrlbarIcon = settings.displayUrlbarIcon;
	enableShortcuts = settings.enableShortcuts;
	parseAnchor = settings.parseAnchor;
	parseDomain = settings.parseDomain; // NOT DEFINED, so false
	parseGetVariables = settings.parseGetVariables;
	// Clear URLs cache
	urlCache = {};
	// Update urlbar icon
	browser.tabs.query({}).then(tabs => {
		for (let tab of tabs) {
			updateUrlbarIcon(tab);
		}
	});
}
```
I just changed the "Update current settings" block by checking if the value are set and equals to `false`:
```javascript
	// Update current settings
	displayUrlbarIcon = !(settings.displayUrlbarIcon === false);
	enableShortcuts = !(settings.enableShortcuts === false);
	parseAnchor = !(settings.parseAnchor === false);
	parseDomain = !(settings.parseDomain === false);
	parseGetVariables = !(settings.parseGetVariables === false);
```
So it should work well with this fix: c02c234a3f8f7493adb5d2161bbed54c3aef16d7  👍

**Pull request merged**
